controllers/ConocenController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Conocen;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ConocenController implements the CRUD actions for Conocen model.
 */
class ConocenController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Conocen models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Conocen::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Conocen model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Conocen model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Conocen();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Conocen model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Conocen model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Conocen model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Conocen the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Conocen::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PreguntasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Preguntas;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PreguntasController implements the CRUD actions for Preguntas model.
 */
class PreguntasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Preguntas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Preguntas::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Preguntas model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Preguntas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Preguntas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Preguntas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Preguntas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Preguntas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Preguntas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Preguntas::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\db\Query;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Usuarios;
use app\models\Personas;
use app\models\Conocen;
use app\models\Direcciones;
use app\models\Numeros;
use app\models\Poblaciones;
use app\models\Preguntas;
use app\models\Provincias;
use app\models\Viven;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login','logout','personaldata','otherdata'],
                'rules' => [
                    [
                        'actions' => ['login','logout','personaldata','otherdata'],
                        'allow' => true,
                        'roles' => ['@'],
                        'denyCallback' => function ($rule, $action) {
                                                 throw new \Exception('Ya está logueado');
                                           }
                    
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionPersonaldata()
    {
        return $this->render('personaldata');
    }
    public function actionOtherdata()
    {
        return $this->render('otherdata');
    }
    
    public function actionUsuarios()
    {
        $query = new Query();
        $query ->select('login,password,ruta_img,id_preguntas,pregunta,respuesta')->from('usuarios');
        $query ->join('INNER JOIN','preguntas','usuarios.id_preguntas = preguntas.id');
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado', [
            "resultados" => $dataProvider,
            "titulo"=>"Listado de todos los usuarios",
            "ruta"=>"../usuarios/index",
            "tabla"=>"Usuarios"
        ]);
    }
     public function actionPersonas()
    {
        $query = new Query();
        $query ->select('DNI,nombre,apellido1,apellido2,fecha_nac,idioma,nacionalidad,login')->from('personas');
        $query ->join('INNER JOIN','usuarios','personas.id_usuario = usuarios.id');
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado', [
            "resultados" => $dataProvider,
            "titulo"=>"Listado de todas las personas",
            "ruta"=>"../personas/index",
            "tabla"=>"Personas"
        ]);
    }
    public function actionNumeros()
    {
        $query = new Query();
        $query ->select('DNI,nombre,num AS numero,esMovil')->from('numeros');
        $query ->join('INNER JOIN', 'personas', 'numeros.id_persona=personas.DNI');
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado', [
            "resultados" => $dataProvider,
            "titulo"=>"Listado de la Agenda",
            "ruta"=>"../numeros/index",
            "tabla"=>"Números"
        ]);
    }
     public function actionProvincias()
    {
        $query = new Query();
        $query ->select('*')->from('provincias');
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado2', [
            "resultados" => $dataProvider,
            "titulo"=>"Províncias de España",
            
            "tabla"=>"Provincias"
        ]);
    }
     public function actionPoblaciones()
    {
        $query = new Query();
        $query ->select('*')->from('poblaciones');
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado2', [
            "resultados" => $dataProvider,
            "titulo"=>"Poblaciones de España",           
            "tabla"=>"Provincias"
        ]);
    }
    public function actionDirecciones()
    {
        $query = new Query();
        $query ->select('id_poblacion,poblaciones.nombre AS poblacion,direcciones.nombre as nombre,numero,CP,comentarios')->from('direcciones');
        $query ->join('INNER JOIN', 'poblaciones', 'direcciones.id_poblacion=poblaciones.id');        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado', [
            "resultados" => $dataProvider,
            "titulo"=>"Listado de direcciones",
            "ruta"=>"../direcciones/index",
            "tabla"=>"Provincias"
        ]);
    }
    public function actionViven()
    {
        $query = new Query();
        $query ->select('id_persona,personas.nombre AS Nombre,apellido1,apellido2,id_direccion,direcciones.nombre AS Direccion,numero,CP,comentarios')->from('viven');
        $query ->join('INNER JOIN', 'personas', 'viven.id_persona=personas.DNI');        
        $query ->join('INNER JOIN', 'direcciones', 'viven.id_direccion=direcciones.id');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        
        return $this->render('resultado', [
            "resultados" => $dataProvider,
            "titulo"=>"Listado de direcciones",
            "ruta"=>"../viven/index",
            "tabla"=>"Provincias"
        ]);
    }
    
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Documentación';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-2 panel panel-primary">
        <div class="panel-heading">
                    <h4>En el documento</h4>
        </div>
        <div class="panel-body">
            <ul class="list-group lista">
                <li class="list-group-item"><a href="#d1">Que es SecureUser</a></li>
                <li class="list-group-item"><a href="#d2">Instalación y acceso al administrador de Yii</a></li>
                <li class="list-group-item"><a href="#d3">Tráfico de datos y encriptación</a></li>
                <li class="list-group-item"><a href="#d4">Código</a></li>
            </ul>
            
        </div>
    </div>
    <div class="col-md-10">
        <div class="site-about panel panel-primary"  style="padding: 4%">
            <div class="panel-heading">
                <h1><?= Html::encode($this->title) ?></h1>
            </div>
            <div class="panel-body panel panel-primary" id="d1">
                <div class="panel-heading">
                    <h3>Que es SecureUser</h3>
                </div>
                <div class="panel-body">
                    <p>SecureUser es un gestor de usuarios creado en PHP.
                    La parte del administrador ha sido enteramente desarrollada sobre Yii.
                    <br/>SecureUser dota de seguridad a cualquier aplicación Web la cual haga uso de administración de usuarios.</p>                    
                </div>                
            </div>
            <div class="panel-body panel panel-success" id="d2">
                <div class="panel-heading">
                    <h3>Instalación y acceso al administrador de Yii</h3>
                </div>
                <div class="panel-body">
                    <h3><u>Instalación</u></h3>
                    <p>Instale xampp y composer.</p>
                    <p>Una vez instalado acceda a la carpeta htdocs/"su-proyecto"/ y cree la carpeta users, dentro de esta y desde su terminal de git corra el siguiente comando.</p>
                    <p>Ejecute el siguiente comando desde la consola de Git dentro de la carpeta yii.</p>
                    <small><code>git clone https://gitlab.com/clase2/proyectofinal.git</code></small>
                    <p>Acceda a la carpeta data y corra el archivo .sql sobre su servidor de MySQL.</p>
                    <div class="panel panel-danger" style="margin:3%; text-align: center">
                        <div class="panel-heading">
                            <h4>Importante</h4>
                        </div>
                        <div class="pannel-body">
                            <p>Para que Yii pueda correr,la rama en git debe ser la<strong> master</strong>.<br/>
                            Si la modifica, este no correrá.</p>
                        </div>
                    </div>
                    <h3><u>Acceso</u></h3>
                    <p>Para acceder solo debe entrar en su buscador y acceder a la carpeta <code>http://"server"/"su-proyecto"/</code>.</p>
                    <p>Para tener acceso al administrador solo debe loguearse en la pestaña de login.</p>
                    <div class="panel-body panel panel-warning">
                        <div class="panel-heading">
                            <h3>Editar las credenciales de los usuarios al gestor</h3>
                            <p><small>"Se recomienda eliminar las credenciales de admin y demo"</small></p>
                        </div>
                        <div class="panel-body">
                            <p>Para editar las credenciales de usuario entre al archivo <code>"/su-proyecto"/models/User.php</code></p>
                            <pre>
private static $users = [                                  _
        '100' => [                                          |
            'id' => '100',                                  |
            'username' => 'admin',       ======>   <strong><u>Nombre</u></strong>   |
            'password' => 'admin',       ======> <strong><u>Contraseña</u></strong> | <strong><u>Usuario 1</u></strong>
            'authKey' => 'test100key',                      |
            'accessToken' => '100-token',                   |
        ],                                                 _|
                                                           _
        '101' => [                                          |
            'id' => '101',                                  |
            'username' => 'demo',                           |
            'password' => 'demo',                           | <strong><u>Usuario 2</u></strong>
            'authKey' => 'test101key',                      |
            'accessToken' => '101-token',                   |
        ],                                                 _|
];
                            </pre>                            
                        </div>
                    </div>                    
                </div>                
            </div>
            <div class="panel-body panel panel-danger" id="d3">
                <div class="panel-heading">
                    <h3>Tráfico de datos y encriptación</h3>
                </div>
                <div class="panel-body">
                    <h3><u>Tráfico de datos</u></h3>
                    <p>Se recomiendan instalar el aplicativo
                    en una máquina independiente</p>
                    <h4><u>Contiene</u></h4>  
                    <ul>
                        <li><h5><u>En esta versión</u></h5> 
                            <ul>
                                <li>Encriptación por SSL</li>
                                <li>Gestor PHP para la I/O de los datos</li>
                            </ul>
                        </li>
                        <li><h5><u>En la siguiente versión</u></h5> 
                            <ul>
                                <li>Encriptación por SSL</li>
                                <li>Encriptación entre el servidor y la DB</li>
                                <li>Gestor PHP para la I/O de los datos</li>
                            </ul>
                        </li>
                    </ul>
                    <div class="panel-body panel panel-success">
                        <div class="panel-heading">
                            <h3>Funciones PHP para el acceso a los datos</h3>
                        </div>
                        <div class="panel-body">
                            <h3><u>Funciones</u></h3>
                            <p>Descripción y uso de las diferentes funciones.</p>
                            <div class="panel-body panel panel-warning">
                                <div class="panel-heading">
                                    <h3>Uso de las funciones PHP para el acceso a los datos</h3>
                                </div>
                                <div class="panel-body">
                                    <p>Para utilizar las funciones instale los archivos php situado en la carpeta <strong>/data/funciones</strong> del gestor.</p>
                                    <p>Para instalar el archivo de funciones siga estos dos sencillos pasos:</p>
                                    <ul>
                                        <li>Cree la carpeta <strong>php</strong> de la siguiente manera: <code>"carpeta de su proyecto web"/<strong>php/</strong></code></li>
                                        <li>Copie los archivo de <strong>/data/funciones</strong> php en la carpeta anteriormente creada</li>
                                        <li>Modifique el archivo <strong>/data/funciones/db.json</strong> ingresando los valores de conexión a su base de datos <small>(la misma sobre la que corren los datos gestionados por Yii)</small>.</li>
                                    </ul>
                                </div>
                            </div>
                            <h3><u>Funciones</u></h3>
                            <ul>
                            <li><p>El archivo dbconn.php crea una conexión segura con la db con lo que se reduce el tiempo de programación</p></li>
                            <h3>Dentro de funciones.php</h3>
                            <li><p><strong>function salidaDatos($query):</strong><br/>Retorna un array(array("nombre de columnas"),array("resultados por columnas"))<br/>Destinada principalmente para select</p></li>
                            <li><p><strong>function entrada($query):</strong> Entradas de $query a base de datos. Retorna "Error" si no se realiza la query</p></li>  
                            <li><p><strong>function comprobarConn():</strong> Retorna el estado de la conexión con la db.</p></li>  
                            <ul>
                        </div>                
                    </div>
                </div>                
            </div>
            <div class="panel-body panel panel-warning" id="d4">
                <div class="panel-heading">
                    <h3>Código</h3>
                </div>
                <div class="panel-body">
                    <p><strong>Licencia: </strong><u>CC0 1.0 Universal (CC0 1.0)
                            Ofrecimiento al Dominio Público</u></p>
                    <div class="panel panel-danger" style="margin:3%; text-align: center">
                        <div class="panel-heading">
                            <h4>Importante</h4>
                        </div>
                        <div class="pannel-body">
                            <p>Este proyecto es puramente libre y gratuito, por favor respete e intente 
                                no comercializar productos a partir de este proyecto.</p>
                        </div>
                    </div>
                    <div class="panel panel-success" style="margin:3%; text-align: center">
                        <div class="panel-heading">
                            <h4>Componentes</h4>
                        </div>
                        <div class="pannel-body">
                            <h4><u>Lenguajes</u></h4>
                            <ul>
                                <li>PHP</li>
                                <li>JavaScripts</li>
                            </ul>
                            <h4><u>Entorno</u></h4>
                            <ul>
                                <li>Yii Framework</li>
                                <li>Composer</li>
                                <li>Xammp server</li>
                            </ul>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
       No se encuentra la página deseada.
    </p>
    <p>
       Por favor revise la URL.
    </p>

</div>

views/site/otherdata.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Tablas adicionales';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-index">
    <br/>
    <div class="jumbotron">
        <h1>Tablas adicionales</h1>

        <p class="lead">Sistema de consultas</p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Provincias</h2>

                    <p><small>Visualización de la tabla provincias</small></p>
                    <p>
                        <?= Html::a('Listas',['/site/provincias'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Poblaciones</h2>

                    <p><small>Visualización de la tabla poblaciones</small></p>
                    <p>
                        <?= Html::a('Listas',['/site/poblaciones'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
           <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Preguntas</h2>

                    <p><small>Visualización de la tabla preguntas</small></p>
                    <p>
                        <?= Html::a('Preguntas',['/preguntas/index'],['class'=>'btn btn-primary'])?>
                    </p>
                  </div>
               </div>
            </div>
        </div>        
    </div>
</div>

views/site/personaldata.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Registros';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-index">
    <br/>
    <div class="jumbotron">
        <h1>Registros</h1>

        <p class="lead">Sistema de consultas</p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Usuarios</h2>

                    <p><small>Visualización de la tabla usuarios</small></p>
                    <p>
                        <?= Html::a('Usuarios',['/usuarios/index'],['class'=>'btn btn-primary'])?>
                        <?= Html::a('Listas',['/site/usuarios'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Personas</h2>

                    <p><small>Visualización de la tabla personas</small></p>
                    <p>
                        <?= Html::a('Personas',['/personas/index'],['class'=>'btn btn-primary'])?>
                        <?= Html::a('Listas',['/site/personas'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Conocen</h2>

                    <p><small>Visualización de la tabla conocen</small></p>
                    <p>
                        <?= Html::a('Conocen',['/conocen/index'],['class'=>'btn btn-primary'])?>
                    </p>
                  </div>
               </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Números</h2>

                    <p><small>Visualización de la tabla numeros</small></p>
                    <p>
                        <?= Html::a('Números',['/numeros/index'],['class'=>'btn btn-primary'])?>
                        <?= Html::a('Listas',['/site/numeros'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Direcciones</h2>

                    <p><small>Visualización de la tabla direcciones</small></p>
                    <p>
                        <?= Html::a('Direcciones',['/direcciones/index'],['class'=>'btn btn-primary'])?>
                        <?= Html::a('Listas',['/site/direcciones'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
            <div class="col-sm-6 col-md-4">
               <div class="thumbnail">
                  <div class="caption">
                    <h2>Viven</h2>

                    <p><small>Visualización de la tabla viven</small></p>
                    <p>
                        <?= Html::a('Viven',['/viven/index'],['class'=>'btn btn-primary'])?>
                        <?= Html::a('Listas',['/site/viven'],['class'=>'btn btn-default'])?>
                    </p>
                  </div>
               </div>
            </div>
        </div>
    </div>
</div>

views/site/resultado.php
<?php

use yii\grid\GridView;
?>

<div>
    <h2>
        <?=$titulo?>
    </h2>
</div>
<div>
    <a href="<?=$ruta?>"><button class="btn btn-success">Modificar tabla <?=$tabla?></button></a>
</div>
<br/>

    <?= GridView::widget([
     'dataProvider'=>$resultados,
    ]);?>